- name: Demo on tags
  hosts: all 
  tasks: 
    - name: Centos
      debug:
        msg: Centos
      tags:
        - centos
    - name: Ubuntu
      debug:
        msg: Ubuntu
      tags: 
        - ubuntu
    - name: Windows
      debug:  
        msg: Windows
      tags:
        - windows
    - name: Linux
      debug:
        msg: Linux
      tags:
        - Linux