- name: Demo on conditions
  hosts: localhost
  vars: 
    OS: Centos
    NUM: 7
  tasks:
    - name: Centos
      debug:
        msg: Centos
      when: OS == "Centos"
      
    - name: Ubuntu
      debug:
        msg: Ubuntu
      when: OS == "ubuntu"
    
    - name: Number Condition - 1
      debug:
        msg: Number Condition - 1
      when : NUM >= 5
        
    - name: Number Condition - 2
      debug:
        msg : Number Condition - 2
      when: NUM <= 5
        