- name: Demo on Variables
  hosts: all 
  vars:
    URL1: play.google.com
  vars_files:
    - vars-file.yml
  tasks:
    - name: Print a variable from play
      debug:
        msg: URL = {{URL1}}
    - name: Print a variable from file
      debug:
        msg: URL = {{URL2}}
    - name : Demo on Task Level vaiables
      vars:
        URL3: task.google.com
      debug:
        msg: URL = {{URL3}}
    - name: Print variables from the host file
      debug:
        msg: URL = {{URL4}}
    - name: Print vaiables from the command line
      debug:
        msg: URL = {{URL5}}
    - name: Run a shell cmd and store output
      shell: uptime
      register: output
    - name: Print uptime output
      debug:
        msg: "{{output.stdout}}"
    - name: Declare a vaiable/facr
      set_fact:
        OUTPUT: "{{output.stdout}}"
    - name: Print OUTPUT variable
      debug:
        msg: "{{OUTPUT}}"