- name: Install Erlang
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm 
    state: present
    
- name: SetUp Yum Repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
  
- name: Install RabbitMQ Server
  yum:
    name: rabbitmq.server
    state: prsent
    
- name: Start RabbitMQ Service
  yum:
    name: rabbitmq.server
    state: started
    enabled: yes
    
- name: Create RoboShop app user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator

    