- name: Create RoboShop App {{COMPONENT}} 
  user:
    name: roboshop
    register: ROBOSHOP_USER
    
- name: Download {{COMPONENT}} App archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
    
- name: Remove old contents
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent
    
- name: Copy extracted contents to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop