- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
              
- name: Create RoboShop App {{COMPONENT}} 
  user:
    name: roboshop
  
- name: Download {{COMPONENT}} App archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
    
- name: Remove old contents
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent
    
- name: Copy extracted contents to {{COMPONENT}} path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop
  
- name: SetUp User Service File
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
  
- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes 

