- name: Install Python
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name:  Download
  include_tasks: download.yml

- name: Install Python Dependencies
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Print User details
  debug:
    msg: "{{ROBOSHOP_USER}}"

# - name: SystemD
#   include_tasks: systemd.yml
  


