- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
              
- name: Create RoboShop App Cart
  user:
    name: roboshop
  
- name: Download Cart App archive
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/cart/archive/main.zip
    dest: /tmp
    remote_src: yes
    
- name: Remove old contents
  ansible.builtin.file:
    path: /home/roboshop/cart
    state: absent
    
- name: Copy extracted contents to Cart path
  ansible.builtin.copy:
    src: /tmp/cart-main/
    dest: /home/roboshop/cart
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/cart
  become_user: roboshop
  
- name: SetUp Cart Service File
  copy:
    src: systemd.service
    dest: /etc/systemd/system/cart.service
  
- name: Start Cart Service
  systemd:
    name: cart
    state: restarted
    enabled: yes
    daemon_reload: yes 

